name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout      
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build projects
      run: ./gradlew assembleDebug

    - name: Run unit test
      run: ./gradlew :launcher:testDebugUnitTest